name: debug

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "docs/**"
      - "README.md"
      - "CHANGELOG.md"
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0

      - name: Get tags
        id: get_tags
        run: |
          echo "tag=$(grep -oP 'version=\K[^ ]+' module.prop)" >> "$GITHUB_OUTPUT"
          echo "version=$(git rev-parse --short HEAD)_$(date +%Y%m%d)" >> "$GITHUB_OUTPUT"
          echo "versionCode=$(date +%Y%m%d)" >> "$GITHUB_OUTPUT"

      - name: update module.prop
        run: |
          sed -i "s/${{ steps.get_tags.outputs.tag }}/&_${{ steps.get_tags.outputs.version }}_debug/g" module.prop
          sed -i "s/versionCode=.*/versionCode=${{ steps.get_tags.outputs.versionCode }}/g" module.prop

      - name: get version
        id: get_version
        run: |
          echo "version=$(grep -oP 'version=\K[^ ]+' module.prop)" >> "$GITHUB_OUTPUT"

      - name: Generate Asset
        run: |
          sudo mkdir -p /box_for_root
          sudo cp -r --parents $(find ./ -type f ! -path './.git/*' ! -name 'CHANGELOG.md' ! -name 'update.json' ! -name 'build.sh' ! -path './.github/*' ! -path './docs/*')  /box_for_root/

      - name: Upload Debug Asset => (box_for_root_debug_${{ steps.get_version.outputs.version }})
        uses: actions/upload-artifact@v3
        with:
          name: "box_for_root_debug_${{ steps.get_version.outputs.version }}"
          path: /box_for_root/


      
