name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true
jobs:
  move-file:  
    name: Move geodata from clash to master  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout clash branch  
        uses: actions/checkout@v3  
        with:  
          ref: clash  
          path: clash 
            
      - name: Checkout master branch  
        uses: actions/checkout@v3  
        with:  
          ref: master  
          path: master 
  
      - name: Copy file_site from clash to master  
        run: |  
          mkdir -p master/box/clash  
          cp clash/geosite-all.dat master/box/clash/GeoSite.dat 
          
      - name: Copy file_ip from clash to master  
        run: |  
          
          cp clash/geoip.metadb master/box/clash/geoip.metadb
          
      - name: Copy file_Country from clash to master  
        run: |  

          cp clash/Country.mmdb master/box/clash/Country.mmdb 
          
      - name: Commit and push changes to master  
        working-directory: master
        run: |  
          git config --global user.email "release@movefile.com"  
          git config --global user.name "GitHub Actions"  
          git add .  
          git commit -m "Move geodata from clash to master as box/clash/~"  
          git push origin master
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Get Version
        id: get_version
        run: |
          echo "date=$(date +%Y%m%d)" >> "$GITHUB_OUTPUT"

      - name: Update update.json and module.prop
        run: |
          echo '{
            "version": "${{ github.event.inputs.tag }}",
            "versionCode": "${{ steps.get_version.outputs.date }}",
            "zipUrl": "https://github.com/LIghtJUNction/clash_meta_config-box4root_config/releases/${{ github.event.inputs.tag }}/box_for_root-${{ github.event.inputs.tag }}.zip",
            "changelog": “https://github.com/LIghtJUNction/clash_meta_config-box4root_config/releases/raw/master/CHANGELOG.md"
          }' > update.json

          sed -i "s/$(grep -oP 'version=\K[^ ]+' module.prop)/${{ github.event.inputs.tag }}/g" module.prop
          sed -i "s/$(grep -oP 'versionCode=\K[^ ]+' module.prop)/$(date +%Y%m%d)/g" module.prop

      - name: run build.sh
        run: |
          sh build.sh


          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: | 
           BoxForRootAlpha-*.zip 
           box/clash/config.yaml
           box/clash/config_参考.yaml
         #  box/clash/ruleset
          generate_release_notes: true

      
