name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Get Version
        id: get_version
        run: |
          echo "date=$(date +%Y%m%d)" >> "$GITHUB_OUTPUT"

      - name: Update update.json and module.prop
        run: |
          echo '{
            "version": "${{ github.event.inputs.tag }}",
            "versionCode": "${{ steps.get_version.outputs.date }}",
            "zipUrl": "https://github.com/LIghtJUNction/clash_meta_config-box4root_config/releases/${{ github.event.inputs.tag }}/box_for_root-${{ github.event.inputs.tag }}.zip",
            "changelog": “https://github.com/LIghtJUNction/clash_meta_config-box4root_config/releases/raw/master/CHANGELOG.md"
          }' > update.json

          sed -i "s/$(grep -oP 'version=\K[^ ]+' module.prop)/${{ github.event.inputs.tag }}/g" module.prop
          sed -i "s/$(grep -oP 'versionCode=\K[^ ]+' module.prop)/$(date +%Y%m%d)/g" module.prop

      - name: run build.sh
        run: |
          sh build.sh
          COMPRESSED_FILE_NAME=$(sh build.sh | grep 'Compressed file name:' | awk '{print $3}')
          - name: Run build.sh and capture output
          echo "Compressed file name is: ${{ steps.build_step.outputs.compressed_file_name }}"


      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: BoxForRootAlpah-v*.zip
          generate_release_notes: true

      
